name: task_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.1+8
  flutter_riverpod: ^2.4.9
  file_picker: ^6.1.1
  another_flushbar: ^1.12.30
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
